name: Build and Release Plugin

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Create plugin ZIP
        run: |
          # Create plugin directory
          mkdir -p rank-math-api-manager

          # Copy plugin files (excluding development files)
          cp -r rank-math-api-manager.php rank-math-api-manager/
          cp -r includes/ rank-math-api-manager/
          cp -r assets/ rank-math-api-manager/
          cp -r docs/ rank-math-api-manager/
          cp README.md rank-math-api-manager/
          cp README-NORWEGIAN.md rank-math-api-manager/
          cp CHANGELOG.md rank-math-api-manager/
          cp CHANGELOG-NORWEGIAN.md rank-math-api-manager/
          cp SECURITY.md rank-math-api-manager/
          cp SECURITY-NORWEGIAN.md rank-math-api-manager/
          cp CODE_OF_CONDUCT.md rank-math-api-manager/
          cp CODE_OF_CONDUCT-NORWEGIAN.md rank-math-api-manager/
          cp LICENSE.md rank-math-api-manager/

          # Create ZIP file
          zip -r rank-math-api-manager-${GITHUB_REF#refs/tags/}.zip rank-math-api-manager/

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./rank-math-api-manager-${GITHUB_REF#refs/tags/}.zip
          asset_name: rank-math-api-manager-${GITHUB_REF#refs/tags/}.zip
          asset_content_type: application/zip
